### PR TITLE
Issue 16

### PR DESCRIPTION
**Pull request by btskinner**
Init and tested `make_cv_df()` function. It's a wrapper for the [tidymodels resampling functions](https://tidymodels.github.io/rsample/reference/index.html), taking arguments as needed. You can use NSE or quoted names for the functions.

_e.g._
```
make_cv_df(df, mc_cv)
make_cv_df(df, mc_cv, times = 50)
make_cv_df(df, "mc_cv")
make_cv_df(df, vfold_cv, v = 20)
```

I've also included a testing framework. You can test the functions either by
```r
## if in the top level directory
testthat::test_dir("./tests/testthat")

## or
setwd("./tests")
source("./testthat.R")
```

### CODE REVIEW

**Comment by btskinner** [comment]
Adding more tests for utility functions and setting up Travis-CI per #11. When it runs, I will probably just merge unless @wdoyle42, you have an issue with my doing that.

**Comment by wdoyle42** [comment]
@btskinner do you think we actually need this above and beyond the existing resample methods from rsample?  I know I filed this issue, and I appreciate the time you spent on it.

**Comment by btskinner** [comment]
What do you mean by this? The function `make_cv_df()`? Probably not, since it's mostly just a wrapper for the various **rsample** methods. I just thought that's what you wanted based on #16. I guess the benefit is that it obscures some of the R code munging we might have to do if we wanted to be able to change resampling methods on the fly with a macro. E.g.,

```r
resample_method <- "mc_cv"
make_cv_df(resample_method)

resample_method <- "vfold_cv"
resample_args <- ...
make_cv_df(resample_method, resample_args)
```

All the Travis check errors right now are b/c Travis doesn't build **rstan** and **rstanarm** well. Since these are requirements of **tidymodels**, I'm getting these errors. I can stop checking for a moment and we can merge w/o issue. But that's if you think the function is useful. If not, can you say more about what you meant?

**Comment by wdoyle42** [comment]
@btskinner --I'm basically questioning whether I should have opened the issue in the first place. Based on what you put together, what do you think?

**Comment by btskinner** [comment]
@wdoyle42, hah! I didn't spend _that_ much time on it. But it's done and contrary to the Travis CI messages, it works. Here's what I see to be the pros and cons:

**Pros**
- We can easily change the resampling method with a macro (per my example)
- We end up with a function that is clear about what it's doing: making a cross-validation data frame (we could change the name)

**Cons**
- It's mostly a wrapper for existing functions
- It obfuscates a bit what is going on under the hood

It will not bother me not at all if we ditch this, though I would keep the branch in case we change our minds.

**Comment by btskinner** [comment]
And now Travis CI works (and checks pass). That said, @wdoyle42, we still don't have to use this function.

**Comment by btskinner** [comment]
@wdoyle42, any more thoughts on this?

**Comment by wdoyle42** [comment]
This works for me-- and this can be integrated into the workflow for #23 .

**Pull request merged**
